### ISSUE TITLE
FR: Add configuration parameter to set PDF file directory

### ISSUE THREAD

**Issue by TomDeSmet** [cooltronicpl/Craft-document-helpers#16]
It would be nice if we could set the directory where we want our PDF's to be saved via a config setting.
Cfr. https://mpdf.github.io/installation-setup/folders-for-temporary-files.html

If I understand correctly, we can do this now by passing a path to the filename argument. However, that doesn't work for me. I need to pass the absolute path to the public folder to be able to write to it (local development).

I also don't think this is good practice as the filename the user sees when downloading the file to his computer now includes the path to the file as well. Which doesn't look nice.

So it would be better in my opinion, if we could specify the path to the directory separate from the filename.

**UPDATE**
Got this working: I had a `/` at the beginning of the filepath/name which resulted in very strange behaviour.
It would still be better I think to separate these two parameters.

**Comment by cooltronicpl** [comment]
So for over 100 hundred people, the plugin may encounter issues when using two parameters because the path with a folder is passed to the plugin in the examples. However, you have the flexibility to save PDFs in any writable path or by using aliases in the examples.

To securely display PDF documents in the browser without saving them to the /web folder, you can follow the instructions provided in the documentation: [Securely Displaying PDF Documents in the Browser Without Saving to the /web Folder](https://github.com/cooltronicpl/Craft-document-helpers/tree/0.2.0#securely-displaying-pdf-documents-in-the-browser-without-saving-to-the-web-folder).

For testing purposes, you can pass entries as `custom` parameters in the `pdfOptions` with your test environment. You have the flexibility to pass any accessible path on your server, such as /tmp or a subfolder within Craft.

Additionally, you can optimize the PDF generation process by exploring the mentioned parameters of MPDF, which may help improve performance. Version 1.1.0 and 0.2.0 of the plugin introduced these optimizations.

However, in most cases, you will be using the @web alias, as the plugin is designed to generate and update multiple PDFs on the first-page load.
