### ISSUE TITLE
Pdf includes CSS

### ISSUE THREAD

**Issue by arentsen** [cooltronicpl/Craft-document-helpers#22]
The pdf generator used to work find, but since a short time (I guess since the plugin update of last week), the pdf text shows the following CSS text on top of the text of the document:

```
Welcome to Craft CMS html, body { font-size: 16px; -webkit-text-size-adjust: 100%; height: 100%;
font-family: system-ui, BlinkMacSystemFont, -apple-system, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif; } body { margin: 0; padding: 0; ETC
```
It shows like this:
<img width="945" alt="Screenshot 2023-11-29 at 13 15 41" src="https://github.com/cooltronicpl/Craft-document-helpers/assets/7302698/697a7b43-91eb-43f2-b40b-52acbc768c1d">

Also, my local installation gives an error message:

`Template „“ could not be found.`

on this line (which is not cached):

`<a href="{{alias('@web')}}/{{craft.documentHelper.pdf("artists/_biography-pdf.twig", "file", 'pdf/' ~ entry.title ~ '-' ~ craft.app.language|upper ~ '.pdf' ,entry, pdfOptions) }}" download target="_blank">Download Bio {{ craft.app.language|upper }}</a`

and the pdfOptions is defined as follows:

```
{% set pdfOptions = {
    header: "/artists/_biography-pdf-header.twig",
    custom: {
       url: entry.url,
       bioTitle: "Biografie"|t,
       langShort: craft.app.language
    },
    footer: ""
} %}
```

**Comment by cooltronicpl** [comment]
Did you use the `date` option?
So we fixed the issue about headers and footers because in many systems it can't be passed, we changed `variable ?? null` into `isset()`.
Do you use a footer template? Because you passed an empty variable into a footer. It can be as not a founded template, and the content of the header (the top) is similar to the default Craft CMS page.
When you use `date` option in pdfOptions your PDF may not be updated for a long time...
Also, the header can be defined as the root of `templates` folder without the slash `/`, so in this example, many of our solutions header and footer templates are defined as the following PDF Options in `_pdf` folder of `templates`:
```
{% set pdfOptions = {
	...
	header: "_pdf/header.twig",
	footer: "_pdf/footer.twig",
	...
	}
%}    
```

**Comment by arentsen** [comment]
Thank you, that is helpful. No, I took out the date function since it did not work, but now it looks like it works again! Thanks for the update.
